<?xml version="1.0" encoding="utf-8"?><Database Name="QLCF" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLCF;Integrated Security=True" SettingsObjectName="QuanLyCaFe.Properties.Settings" SettingsPropertyName="QLCFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenhienthi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password1" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="loaitaikhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ngayvao" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="idBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bill_ThongTinBill" Member="ThongTinBills" ThisKey="id" OtherKey="idBill" Type="ThongTinBill" />
      <Association Name="TableFood_Bill" Member="TableFood" ThisKey="idBan" OtherKey="id" Type="TableFood" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Food" Member="Foods">
    <Type Name="Food">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenmon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="idCategory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Food_ThongTinBill" Member="ThongTinBills" ThisKey="id" OtherKey="idMon" Type="ThongTinBill" />
      <Association Name="FoodCategory_Food" Member="FoodCategory" ThisKey="idCategory" OtherKey="id" Type="FoodCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FoodCategory" Member="FoodCategories">
    <Type Name="FoodCategory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="FoodCategory_Food" Member="Foods" ThisKey="id" OtherKey="idCategory" Type="Food" />
    </Type>
  </Table>
  <Table Name="dbo.TableFood" Member="TableFoods">
    <Type Name="TableFood">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenban" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TableFood_Bill" Member="Bills" ThisKey="id" OtherKey="idBan" Type="Bill" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTinBill" Member="ThongTinBills">
    <Type Name="ThongTinBill">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBill" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idMon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bill_ThongTinBill" Member="Bill" ThisKey="idBill" OtherKey="id" Type="Bill" IsForeignKey="true" />
      <Association Name="Food_ThongTinBill" Member="Food" ThisKey="idMon" OtherKey="id" Type="Food" IsForeignKey="true" />
    </Type>
  </Table>
</Database>